title: "&8-=( &2Champion Settings &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&b升级装备"
    material: DIAMOND_CHESTPLATE
    sounds:
      max-level: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7提高国土的圣贤"
      - "每次升级可提升盔甲和武器的强度."
      - ""
      - "&2等级&8: &6%level%"
      - "&2资源点&8: &6%cost%"
    slot: 0
  change:
    name: "&6外观"
    material: DIAMOND_SWORD
    lore:
      - "&7改变圣贤的外观类型."
    slot: 1

  back:
    name: "&2返回"
    material: BARRIER
    lore:
      - "&6返回到上个界面进行升级吧."
    slot: 4