title: "&8-=( &7Settings &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Shield&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Buy a shield for your"
      - "nation to protect your nation"
    posx: 1
    posy: 1
  invites:
    name: "&6Invites&8: %invites%"
    material: BOOK
    lore:
      - "&7When turned off, anyone can"
      - "join this nation without needing"
      - "an invitation with &2/k nation join %kingdoms_nation%"
    posx: 2
    posy: 1
  relations:
    name: "&6Relations"
    material: WRITABLE_BOOK
    lore:
      - "&7Change your relation attributes"
      - "for other nations."
    posx: 3
    posy: 1
  tax:
    name: "&6Tax"
    material: PAPER
    lore:
      - "&7Change your nation taxes"
      - "for kingdoms."
      - ""
      - "&6Tax&8: &2$%kingdoms_fancy_nation_tax%"
      - "&6Equation&8: &2%tax_equation%"
      - ""
      - "&6Billing Tax&8: &2$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Back"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Go back to nexus menu."
    posx: 9
    posy: 1